// 手写虚拟列表/virtua-list.vue
<!-- FsVirtualList.vue -->
<template>
    <div class="container">
        <div ref="containerRef" class="fs-virtuallist-container" @scroll="handleScroll">
            <div class="fs-virtuallist-list" :style="scrollStyle">
                <div v-for="item in renderList" :key="item" class="fs-virtuallist-item">
                    {{ item }}
                </div>
            </div>
        </div>
    </div>
</template>

<script setup>
import { ref, reactive, computed, onMounted, nextTick } from 'vue'

// ---------- 状态定义 ----------
const state = reactive({
    dataSource: [],        // 模拟数据源
    itemHeight: 100,       // 固定 item 高度 (px)
    viewHeight: 0,         // container 高度
    maxCount: 0,           // 虚拟列表视图最大容纳量
})

const containerRef = ref(null)  // 容器 DOM 引用
const startIndex = ref(0)       // 当前视图起始索引
const lastStart = ref(0)        // 上次起始索引，用于判断是否重新渲染

// ---------- 计算属性 ----------
// 计算当前视图结束索引
const endIndex = computed(() => {
    const end = startIndex.value + state.maxCount
    return end < state.dataSource.length ? end : state.dataSource.length
})

// 计算当前要渲染的列表
const renderList = computed(() => {
    return state.dataSource.slice(startIndex.value, endIndex.value)
})

// 计算滚动容器的样式（高度 + 偏移）
const scrollStyle = computed(() => {
    const { dataSource, itemHeight } = state
    const totalHeight = dataSource.length * itemHeight
    const offset = startIndex.value * itemHeight

    return {
        height: `${totalHeight - offset}px`,      // 剩余高度撑开滚动条
        transform: `translate3d(0, ${offset}px, 0)` // Y轴偏移
    }
})

// ---------- 方法 ----------
// 添加更多数据（模拟滚动到底部加载）
const addData = () => {
    for (let i = 0; i < 10; i++) {
        state.dataSource.push(state.dataSource.length + 1)
    }
}

// 检查是否需要添加数据（当 endIndex 接近末尾时）
const checkAddData = () => {
    if (endIndex.value >= state.dataSource.length - 1) {
        addData()
    }
}

// 滚动事件处理（带 raf 节流）
const handleScroll = () => {
    if (!containerRef.value) return

    const scrollTop = containerRef.value.scrollTop
    const newStartIndex = Math.floor(scrollTop / state.itemHeight)

    if (newStartIndex !== startIndex.value) {
        startIndex.value = newStartIndex
        // 这里不需要手动调 render，因为计算属性会响应式更新
        // 但需要检查是否需要加载更多数据
        checkAddData()
    }
}

// 初始化容器高度和 maxCount
const init = () => {
    if (!containerRef.value) return

    // 获取容器实际高度
    state.viewHeight = containerRef.value.offsetHeight
    // 计算最多能渲染多少个 item（向上取整 + 1 作为缓冲区）
    state.maxCount = Math.ceil(state.viewHeight / state.itemHeight) + 1

    // 初始添加数据
    addData()
}

// ---------- 生命周期 ----------
onMounted(() => {
    init()
})
</script>

<style scoped>
.container {
    width: 600px;
    height: 600px;
    margin: 100px auto;
    border: 1px solid red;
}

.fs-virtuallist-container {
    width: 100%;
    height: 100%;
    overflow-y: auto;
}

.fs-virtuallist-list {
    width: 100%;
    position: relative;
    /* 确保 transform 生效 */
}

.fs-virtuallist-item {
    width: 100%;
    height: 100px;
    box-sizing: border-box;
    border: 1px solid #000;
    text-align: center;
    font-size: 20px;
    line-height: 100px;
}
</style>

// 手写虚拟列表/virtua-list.jsx
import React, {
  useState,
  useEffect,
  useRef,
  useCallback,
  useMemo,
} from "react";
import "./FsVirtualList.css"; // 样式文件（见下文）

const FsVirtualList = () => {
  // ---------- 状态定义 ----------
  const [dataSource, setDataSource] = useState([]);
  const [viewHeight, setViewHeight] = useState(0);
  const [startIndex, setStartIndex] = useState(0);

  // 固定配置
  const itemHeight = 100;

  // DOM 引用
  const containerRef = useRef(null);

  // 计算最大容纳量
  const maxCount = useMemo(() => {
    return Math.ceil(viewHeight / itemHeight) + 1;
  }, [viewHeight]);

  // 计算结束索引
  const endIndex = useMemo(() => {
    const end = startIndex + maxCount;
    return end < dataSource.length ? end : dataSource.length;
  }, [startIndex, maxCount, dataSource.length]);

  // 计算当前渲染列表
  const renderList = useMemo(() => {
    return dataSource.slice(startIndex, endIndex);
  }, [dataSource, startIndex, endIndex]);

  // 计算滚动样式
  const scrollStyle = useMemo(() => {
    const totalHeight = dataSource.length * itemHeight;
    const offset = startIndex * itemHeight;

    return {
      height: `${totalHeight - offset}px`,
      transform: `translate3d(0, ${offset}px, 0)`,
    };
  }, [dataSource.length, startIndex, itemHeight]);

  // ---------- 辅助函数 ----------
  // 添加更多数据
  const addData = useCallback(() => {
    setDataSource((prev) => {
      const newData = [];
      for (let i = 0; i < 10; i++) {
        newData.push(prev.length + i + 1);
      }
      return [...prev, ...newData];
    });
  }, []);

  // 检查是否需要加载更多
  const checkAddData = useCallback(() => {
    if (endIndex >= dataSource.length - 1) {
      addData();
    }
  }, [endIndex, dataSource.length, addData]);

  // 滚动处理
  const handleScroll = useCallback(() => {
    if (!containerRef.current) return;

    const scrollTop = containerRef.current.scrollTop;
    const newStartIndex = Math.floor(scrollTop / itemHeight);

    if (newStartIndex !== startIndex) {
      setStartIndex(newStartIndex);
      // 在下次渲染后检查是否需要加载更多
      setTimeout(checkAddData, 0);
    }
  }, [startIndex, itemHeight, checkAddData]);

  // 节流处理（使用 requestAnimationFrame）
  const throttledScroll = useCallback(() => {
    let ticking = false;

    return () => {
      if (!ticking) {
        window.requestAnimationFrame(() => {
          handleScroll();
          ticking = false;
        });
        ticking = true;
      }
    };
  }, [handleScroll]);

  // ---------- 初始化 ----------
  useEffect(() => {
    if (containerRef.current) {
      // 获取容器高度
      setViewHeight(containerRef.current.offsetHeight);
      // 初始添加数据
      addData();
    }
  }, [addData]);

  // 监听 scroll 事件
  useEffect(() => {
    const container = containerRef.current;
    if (!container) return;

    const scrollHandler = throttledScroll();
    container.addEventListener("scroll", scrollHandler);

    return () => {
      container.removeEventListener("scroll", scrollHandler);
    };
  }, [throttledScroll]);

  // 当数据源变化时，检查是否需要立即加载更多（处理快速滚动到底部的情况）
  useEffect(() => {
    checkAddData();
  }, [endIndex, checkAddData]);

  return (
    <div className="container">
      <div ref={containerRef} className="fs-virtuallist-container">
        <div className="fs-virtuallist-list" style={scrollStyle}>
          {renderList.map((item) => (
            <div key={item} className="fs-virtuallist-item">
              {item}
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};


export default FsVirtualList;
